Repository FRONTENDBOOTCAMP-13th/Final-05-oguogu, pull requests merged in 2025-07, with the labels that each got.

#13 ✨ feat: 카테고리 UI 컴포넌트 작업 완료
  src/app/globals.css
  src/app/page.tsx
  src/components/elements/CategoryItem/CategoryItem.tsx
  src/components/elements/CategoryItem/CategoryItem.type.tsx
  src/components/layouts/Category/Category.tsx
Labels: enhancement

#17 🐳 chore: Github 이슈 탬플릿 Type 지정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/task.md
Labels: Task: 기타

#22 Feat/navigation/ws
  package-lock.json
  package.json
  src/app/globals.css
  src/app/page.tsx
  src/components/elements/NavigationItem/NavigationItem.tsx
  src/components/elements/NavigationItem/NavigationItem.type.tsx
  src/components/layouts/Navigation/Navigation.tsx
Labels: ✅ Task: 기능 개발

#32 📝 docs: 카테고리/태그/장바구니 상태 코드 정의 및 JSON 파일 추가
  src/shared/data/categoryData.json
Labels: ✅ Task: 문서화

#40 ✨feat : SlideBanner 컴포넌트 UI 완성
  src/app/page.tsx
  src/components/elements/BannerItem/SlideBannerItem.tsx
  src/components/elements/BannerItem/SlideBannerItem.type.tsx
  src/components/layouts/Banner/SlideBanner.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#47 ✨feat: 공통 버튼 컴포넌트 UI 구현
  src/app/page.tsx
  src/components/elements/CommonButton/CommonButton.tsx
  src/components/elements/CommonButton/CommonButton.type.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#49 🐳 chore: 라우팅 폴더 구조 확인 및 컴포넌트 함수 내 텍스트 개선
  src/app/(accounts)/(seller)/office/page.tsx
  src/app/(accounts)/(user)/mypage/page.tsx
  src/app/(accounts)/account/page.tsx
  src/app/(accounts)/register/page.tsx
  src/app/(exploring)/product/[type]/[category]/page.tsx
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/page.tsx
Labels: Task: 기타

#52 ✨feat: 개별 아이템 UI (작업 중 재현님께 토스)
  public/images/crop/crop-001.png
  public/images/experience/experience-001.png
  src/components/elements/ProductItem/CropItem/CropItem.tsx
  src/components/elements/ProductItem/CropItem/CropItem.type.tsx
  src/components/elements/ProductItem/ExperienceItem/.gitkeep
  src/components/elements/ProductItem/SubscribeItem/.gitkeep
Labels: ✅ Task: 기능 개발, 🔴 Priority: High, ✅ Task: UI 개선

#56 ✨ feat: 회원가입 타입별 선택 컴포넌트 UI 구현
  public/images/register/register-seller.svg
  public/images/register/register-user.svg
  src/app/(accounts)/register/page.tsx
  src/components/elements/RegisterItem/RegisterCardItem.tsx
  src/shared/data/actions/product.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#57 Feat/badge/ws
  src/app/globals.css
  src/app/page.tsx
  src/components/elements/CommonButton/CommonButton.tsx
  src/components/elements/CommonButton/CommonButton.type.tsx
  src/components/elements/ProductItem/Badge/Badge.tsx
  src/components/elements/ProductItem/Badge/Badge.type.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#59 ✨ feat: 일반 상품 컴포넌트 UI 작업 완료
  public/images/product-hatIcon.svg
  src/app/(exploring)/product/[type]/page.tsx
  src/components/elements/InteractionButton/InteractionButton.tsx
  src/components/elements/ProductItem/Badge/Badge.tsx
  src/components/elements/ProductItem/CropItem/CropItem.tsx
  src/components/elements/ProductItem/CropItem/CropItem.type.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#70 ✨feat : 상품 경로 컴포넌트 UI 구현
  public/svgs/arrow-right.svg
  src/app/page.tsx
  src/components/elements/Path/Path.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#72 ✨feat : 구매 버튼 모달 팝업 컴포넌트 UI 완성
  package-lock.json
  package.json
  src/app/(exploring)/product/[type]/[category]/[_id]/page.tsx
  src/components/elements/BuyBoxForMobile/BuyBoxOption.tsx
  src/components/elements/BuyBoxForMobile/BuyBoxOption.type.tsx
  src/components/elements/BuyBoxForMobile/BuyBoxOptionExtraItem.tsx
  src/components/elements/BuyBoxForMobile/BuyBoxOptionExtraItem.type.tsx
  tailwind.config.js
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선, Task: 기타

#73 ✨ feat: [상품 리뷰 관련, 메인페이지 Title, 상세 페이지 하단 구매 버튼] 컴포넌트 UI 완료
  public/images/iconImage/icon-end.svg
  public/images/iconImage/icon-remain.svg
  public/images/iconImage/icon-star-empty.svg
  public/images/iconImage/icon-star-filled.svg
  public/images/iconImage/icon-start.svg
  src/app/(exploring)/product/[type]/page.tsx
  src/components/elements/BuyBox/BuyBox.tsx
  src/components/elements/CommonTitleItem/Title.tsx
  src/components/elements/ProductItem/SubscribeItem/GardenItem.tsx
  src/components/elements/ProductItem/SubscribeItem/GardenItemIcon.tsx
  src/components/elements/QnaItem/QnaItem.tsx
  src/components/elements/ReviewItem/ReviewItem.tsx
  src/components/elements/ReviewItem/StarRating.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#81 ✨ feat: 메인 페이지 UI 1차 완성
  public/images/category-fruit.webp
  public/images/category-grain.webp
  public/images/category-mushroom.webp
  public/images/category-veggie.webp
  src/app/page.tsx
  src/components/elements/BannerItem/SlideBannerItem.tsx
  src/components/elements/CategoryItem/CategoryItem.type.tsx
  src/components/elements/CommonButton/CommonButton.tsx
  src/components/elements/CommonButton/CommonButton.type.tsx
  src/components/elements/CommonTitleItem/Title.tsx
  src/components/elements/InteractionButton/InteractionButton.tsx
  src/components/elements/ProductItem/CropItem/CropItem.tsx
  src/components/elements/ProductItem/ExperienceItem/ExperienceItem.tsx
  src/components/elements/ProductLink/ProductLink.tsx
  src/components/elements/ProductLink/ProductLink.type.tsx
  src/components/layouts/Banner/SlideBanner.tsx
  src/components/layouts/Category/Category.tsx
  src/components/layouts/Header/Header.tsx
  src/components/layouts/Navigation/Navigation.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#89 ✨ feat: 상세페이지 기본 UI 구현 완료
  src/app/(exploring)/product/[type]/[category]/[_id]/detail/page.tsx
  src/app/(exploring)/product/[type]/[category]/[_id]/layout.tsx
  src/app/(exploring)/product/[type]/[category]/[_id]/page.tsx
  src/app/(exploring)/product/[type]/[category]/[_id]/qna/page.tsx
  src/app/(exploring)/product/[type]/[category]/[_id]/review/page.tsx
  src/app/(exploring)/product/[type]/page.tsx
  src/app/page.tsx
  src/components/elements/BuyBox/BuyBox.tsx
  src/components/elements/BuyBoxForMobile/BuyBoxOption.tsx
  src/components/elements/BuyModal/BuyModal.tsx
  src/components/elements/CommonTitleItem/Title.tsx
  src/components/elements/ProductDetailInfo/ProductDetailInfo.tsx
  src/components/elements/ProductLink/ProductLink.tsx
  src/components/layouts/Category/Category.tsx
  src/components/layouts/Header/Header.tsx
  src/components/layouts/Header/SearchHeader.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#99 ♻️ refactor: 1차 배포건 리팩토링 및 반응형 스타일링 통일 작업
  public/images/image.png
  public/images/qr.png
  src/app/(accounts)/(user)/mypage/cart/page.tsx
  src/app/(accounts)/(user)/mypage/order/page.tsx
  src/app/(accounts)/(user)/mypage/page.tsx
  src/app/(accounts)/(user)/mypage/pick/page.tsx
  src/app/(accounts)/(user)/mypage/subscribe/page.tsx
  src/app/(accounts)/account/edit/page.tsx
  src/app/(accounts)/account/page.tsx
  src/app/(accounts)/login/page.tsx
  src/app/(accounts)/login/register/page.tsx
  src/app/(accounts)/register/page.tsx
  src/app/(accounts)/register/seller/page.tsx
  src/app/(accounts)/register/user/page.tsx
  src/app/(exploring)/garden/[seller_id]/page.tsx
  src/app/(exploring)/product/[type]/[category]/[_id]/layout.tsx
  src/app/(exploring)/product/[type]/[category]/page.tsx
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/result/[_id]/detail/page.tsx
  src/app/(exploring)/search/result/[_id]/layout.tsx
  src/app/(exploring)/search/result/[_id]/qna/page.tsx
  src/app/(exploring)/search/result/[_id]/review/page.tsx
  src/app/(exploring)/search/result/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/elements/BannerItem/SlideBannerItem.tsx
  src/components/elements/BannerItem/SlideBannerItem.type.tsx
  src/components/elements/BuyBox/BuyBox.tsx
  src/components/elements/BuyBoxForMobile/BuyBoxOption.tsx
  src/components/elements/BuyBoxForMobile/BuyBoxOptionExtraItem.tsx
  src/components/elements/BuyModal/BuyModal.tsx
  src/components/elements/CategoryItem/CategoryItem.tsx
  src/components/elements/CategoryItem/CategoryItem.type.tsx
  src/components/elements/CheckButton/CheckButton.tsx
  src/components/elements/CommonTitleItem/Title.tsx
  src/components/elements/LoginItem/LoginInput.tsx
  src/components/elements/NavigationItem/NavigationItem.tsx
  src/components/elements/Path/Path.tsx
  src/components/elements/ProductDetailInfo/ProductDetailInfo.tsx
  src/components/elements/ProductItem/CropItem/CropItem.tsx
  src/components/elements/ProductItem/ExperienceItem/ExperienceItem.tsx
  src/components/elements/ProductItem/Filter/Filter.tsx
  src/components/elements/ProductItem/Filter/Filter.type.ts
  src/components/elements/ProductLink/ProductLink.tsx
  src/components/elements/ProductLink/ProductLink.type.tsx
  src/components/elements/QnaItem/QnaItem.tsx
  src/components/elements/ReviewItem/ReviewItem.tsx
  src/components/layouts/Category/Category.tsx
  src/components/layouts/Header/CategoryHeader.tsx
  src/components/layouts/Header/Header.tsx
  src/components/layouts/Header/LinkHeader.tsx
  src/components/layouts/Header/SearchHeader.tsx
  src/components/layouts/Header/types/Header.type.ts
  src/components/layouts/Header/utils/handleGoBack.ts
  src/components/layouts/Navigation/Navigation.tsx
  src/components/layouts/SortBar/Sortbar.tsx
Labels: 🔴 Priority: High, ✅ Task: UI 개선, 🛠️ Task: 리팩토링, ⚙️ Task: 리팩토링

#100 ✨ feat: 상품 탐색 목록 페이지 및 상품 검색 결과 페이지 UI 스타일링 완성
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/result/page.tsx
  src/components/elements/CommonTitleItem/Title.tsx
  src/components/elements/ProductItem/ExperienceItem/.gitkeep
  src/components/elements/ProductItem/Item/CropItem.tsx
  src/components/elements/ProductItem/Item/ExperienceItem.tsx
  src/components/elements/ProductItem/Item/GardenItem.tsx
  src/components/elements/ProductItem/Item/GardenItemIcon.tsx
  src/components/elements/ProductItem/Item/Item.type.tsx
  src/components/elements/ProductItem/SubscribeItem/.gitkeep
  src/components/layouts/Header/CategoryHeader.tsx
  src/components/layouts/Header/SearchHeader.tsx
Labels: ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#103 ✨feat : 회원가입 페이지 UI 구현
  src/app/(accounts)/login/page.tsx
  src/app/(accounts)/register/page.tsx
  src/app/(accounts)/register/seller/page.tsx
  src/app/(accounts)/register/user/page.tsx
  src/components/elements/CheckButton/CheckButton.tsx
  src/components/elements/CommonButton/CommonButton.tsx
  src/components/elements/CommonButton/CommonButton.type.tsx
  src/components/elements/LoginItem/LoginInput.tsx
  src/components/elements/LoginItem/LoginInput.type.tsx
  src/components/elements/ProductLink/ProductLink.tsx
  src/components/elements/ProductLink/ProductLink.type.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#112 ♻️ refactor: 상품 검색 결과 및 상품 탐색 목록 페이지 개선
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/result/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/elements/BuyBoxForMobile/BuyBoxOption.tsx
  src/components/elements/CategoryItem/CategoryItem.tsx
  src/components/elements/InteractionButton/InteractionButton.tsx
  src/components/layouts/Header/CategoryHeader.tsx
Labels: ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#121 ♻️ refactor 상세페이지 코드 정리
  src/app/(exploring)/search/result/[_id]/detail/page.tsx
  src/app/(exploring)/search/result/[_id]/layout.tsx
  src/app/(exploring)/search/result/[_id]/qna/page.tsx
  src/app/(exploring)/search/result/[_id]/review/page.tsx
  src/components/elements/BuyBox/ButBox.type.ts
  src/components/elements/BuyBox/BuyBox.tsx
  src/components/elements/BuyModal/BuyModal.tsx
  src/components/elements/BuyModal/BuyModal.type.ts
  src/components/elements/CommonTitleItem/Title.type.ts
  src/components/elements/ProductDetailInfo/ProductDetailInfo.tsx
  src/components/elements/ProductDetailInfo/ProductDetailInfo.type.ts
  src/components/elements/ReviewItem/ReviewItem.tsx
  src/components/elements/ReviewItem/ReviewItem.type.ts
  src/components/layouts/Category/Category.tsx
  src/components/layouts/SortBar/Sortbar.tsx
  src/components/layouts/SortBar/Sortbar.type.ts
  src/features/buyModal/buyModalAction.tsx
  src/features/qnaClientControl/qnaClientControl.tsx
  src/features/reviewClientControl/reviewClientControl.tsx
  src/features/types/productDetail.ts
  src/shared/data/actions/bookmarks.ts
  src/shared/types/product.ts
Labels: ⚙️ Task: 리팩토링

#124 🚑 hotfix: 빌드 오류건 수정
  src/app/(exploring)/search/page.tsx
  src/app/(exploring)/search/result/page.tsx
  src/app/page.tsx
  src/components/layouts/Header/CategoryHeader.tsx
Labels: 🐛 Task: 버그 해결

#127 ✨ feat: /product/[type] 동적 라우팅 경로 추가
  src/app/(exploring)/product/[type]/ProductListByType.type.ts
  src/app/(exploring)/product/[type]/not-found.tsx
  src/app/(exploring)/product/[type]/page.tsx
Labels: ✅ Task: 기능 개발

#129 ✨feat : 로그인 기능 구현 , 코드 리팩토링
  src/app/(accounts)/login/page.tsx
  src/components/elements/CommonButton/CommonButton.tsx
  src/components/elements/CommonButton/CommonButton.type.tsx
  src/components/elements/LoginItem/LoginInput.tsx
  src/components/layouts/Login/LoginForm.tsx
Labels: ✅ Task: 기능 개발, 🔴 Priority: High

#131 ✨ feat: CategoryHeader 기능 완성
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/page.tsx
  src/app/(exploring)/search/result/[_id]/detail/page.tsx
  src/app/(exploring)/search/result/[_id]/layout.tsx
  src/app/(exploring)/search/result/page.tsx
  src/components/elements/InteractionButton/InteractionButton.tsx
  src/components/elements/LoginItem/LoginInput.tsx
  src/components/elements/ProductItem/Item/CropItem.tsx
  src/components/layouts/Header/CategoryHeader.tsx
  src/components/layouts/Header/types/Header.type.ts
Labels: ✅ Task: 기능 개발, ⚙️ Task: 리팩토링

#135 ✨ feat: 상품 관련 페이지 DB 기능 연결
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/result/[_id]/qna/page.tsx
  src/app/(exploring)/search/result/[_id]/review/page.tsx
  src/app/(exploring)/search/result/page.tsx
  src/components/elements/InteractionButton/InteractionButton.tsx
  src/components/elements/LinkIcon/LinkIcon.tsx
  src/components/elements/ProductItem/Item/CropItem.tsx
  src/components/elements/ProductItem/Item/ExperienceItem.tsx
  src/components/elements/ProductItem/Item/GardenItem.tsx
  src/components/elements/ProductItem/Item/Item.type.tsx
  src/components/elements/ProductItem/List/ProductItemList.tsx
  src/components/layouts/SortBar/Sortbar.tsx
  src/shared/data/functions/bookmarks.ts
  src/shared/store/bookmarkStore.ts
  src/shared/types/bookmarkt.ts
  src/shared/types/product.ts
Labels: 🐛 Task: 버그 해결, ✅ Task: 기능 개발, ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#136 ✨feat : 회원가입 기능 구현
  src/app/(accounts)/register/seller/page.tsx
  src/app/(accounts)/register/user/page.tsx
Labels: ✅ Task: 기능 개발

#139 ✨ feat: 마이페이지 하위 페이지 기본 레이아웃 완성
  next.config.ts
  src/app/(accounts)/(user)/mypage/cart/page.tsx
  src/app/(accounts)/(user)/mypage/gardening/page.tsx
  src/app/(accounts)/(user)/mypage/layout.tsx
  src/app/(accounts)/(user)/mypage/order/page.tsx
  src/app/(accounts)/(user)/mypage/page.tsx
  src/app/(accounts)/(user)/mypage/pick/page.tsx
  src/app/(accounts)/(user)/mypage/subscribe/page.tsx
  src/components/elements/DeleteButton/DeleteButton.tsx
  src/components/elements/HamburgerIcon/HamburgerIcon.tsx
  src/components/elements/InputButtonForMypage/InputButtonForMypage.tsx
  src/components/elements/InputButtonForMypage/InputButtonForMypage.type.ts
  src/components/elements/IsEmptyMessage/IsEmptyMessage.tsx
  src/components/elements/IsEmptyMessage/IsEmptyMessage.type.ts
  src/components/elements/LinkIcon/LinkIcon.type.ts
  src/components/elements/ProductDetailInfo/ProductDetailInfo.tsx
  src/components/elements/ShareIcon/ShareIcon.tsx
  src/components/elements/ShareIcon/ShareIcon.type.ts
  src/components/layouts/Header/CategoryHeader.tsx
  src/components/layouts/Header/Header.tsx
  src/components/layouts/Header/LinkHeader.tsx
  src/components/layouts/Header/ProductHeader.tsx
  src/components/layouts/Header/SearchHeader.tsx
  src/components/layouts/Header/types/Header.type.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#144 ✨ feat: TopRatedItem DB 반영 작업 완료 (검색 최종 기능 구현 작업 예정)
  src/app/(exploring)/search/page.tsx
  src/components/elements/TopRatedItem/TopRatedItem.tsx
  src/shared/data/functions/user.ts
  src/shared/types/user.ts
Labels: ✅ Task: 기능 개발, ⚙️ Task: 리팩토링

#148 ✨ feat: 주문/배송 페이지 기능 구현 완료
  src/app/(accounts)/(user)/mypage/order/page.tsx
  src/components/elements/CuteLoading/CuteLoading.tsx
  src/components/elements/DeleteButton/DeleteButton.tsx
  src/components/elements/HamburgerIcon/HamburgerIcon.tsx
  src/components/elements/InputButtonForMypage/InputButtonForMypage.tsx
  src/components/elements/IsEmptyMessage/IsEmptyMessage.tsx
  src/components/elements/IsEmptyMessage/IsEmptyMessage.type.ts
  src/components/elements/OrderItem/OrderItem.tsx
  src/components/elements/OrderItem/OrderItem.type.ts
  src/features/orderClientControl/orderClientControl.tsx
  src/shared/data/actions/order.ts
  src/shared/data/functions/order.ts
  src/shared/types/order.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#152 ✨feat : 찜한 상품 페이지 DB 반영
  src/app/(accounts)/(user)/mypage/pick/page.tsx
  src/components/elements/InputButtonForMypage/InputButtonForMypage.tsx
  src/components/elements/InputButtonForMypage/InputButtonForMypage.type.ts
  src/features/pickList/pickList.tsx
Labels: ✅ Task: 기능 개발, ⚙️ Task: 리팩토링

#150 ✨ feat: 장바구니 기능 구현 완료
  src/app/(accounts)/(user)/mypage/cart/page.tsx
  src/components/elements/BuyModal/BuyModal.tsx
  src/components/elements/DeleteButton/DeleteButton.tsx
  src/components/elements/InputButtonForMypage/InputButtonForMypage.tsx
  src/components/elements/InputButtonForMypage/InputButtonForMypage.type.ts
  src/components/elements/cardItem/cardItem.tsx
  src/components/layouts/Header/CategoryHeader.tsx
  src/features/cartClientControl/cartClientControl.tsx
  src/shared/data/actions/cart.ts
  src/shared/data/functions/cart.ts
  src/shared/types/cart.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#157 🩹 fix: 햄버거 버튼 로그인 상태에 따른 페이지 라우팅 경로 수정건 삭제
  src/components/elements/HamburgerIcon/HamburgerIcon.tsx
Labels: ⚙️ Task: 리팩토링

#159 🚑 Hotfix : 로그인 페이지/회원가입 페이지 개선
  src/app/(accounts)/register/seller/registerForm.tsx
  src/app/(accounts)/register/user/page.tsx
  src/app/(accounts)/register/user/registerForm.tsx
  src/components/elements/LoginItem/LoginInput.tsx
Labels: 🐛 Task: 버그 해결, ⚙️ Task: 리팩토링

#160 🐛 hotfix: 2차 배포 전 오류건 해결
  src/app/(accounts)/(user)/mypage/cart/page.tsx
  src/app/(accounts)/(user)/mypage/checkout/page.tsx
  src/app/(accounts)/(user)/mypage/gardening/page.tsx
  src/app/(accounts)/(user)/mypage/layout.tsx
  src/app/(accounts)/(user)/mypage/order/page.tsx
  src/app/(accounts)/(user)/mypage/page.tsx
  src/app/(accounts)/(user)/mypage/pick/page.tsx
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/result/page.tsx
  src/app/board/notice/page.tsx
  src/app/board/qna/page.tsx
  src/app/page.tsx
  src/components/elements/BuyModal/BuyModal.tsx
  src/components/elements/CategoryItem/CategoryItem.tsx
  src/components/elements/LogoutIcon/LogoutIcon.tsx
  src/components/elements/ProductDetailInfo/ProductDetailInfo.tsx
  src/components/elements/ProductItem/Item/CropItem.tsx
  src/components/elements/ProductItem/Item/ExperienceItem.tsx
  src/components/elements/ProductItem/Item/GardenItem.tsx
  src/components/elements/ProductItem/List/ProductItemList.tsx
  src/components/layouts/Header/CategoryHeader.tsx
  src/components/layouts/Header/Header.tsx
  src/components/layouts/Header/LinkHeader.tsx
  src/components/layouts/Header/ProductHeader.tsx
  src/components/layouts/Header/SearchHeader.tsx
  src/features/buyModal/buyModalAction.tsx
  src/features/cartItemCountIcon/CartItemCountIcon.tsx
  src/features/goBackIcon/goBackIcon.tsx
  src/features/pickList/pickList.tsx
  src/shared/types/product.ts
  src/utils/getDiffDays/getDiffDays.tsx
Labels: ✅ Task: 기능 개발, ⚙️ Task: 리팩토링

#169 ✨ feat: 주문 페이지 렌더링 오류 해결 완료
  src/components/elements/OrderItem/OrderItem.tsx
Labels: ⚙️ Task: 리팩토링

#174 ✨ feat: 장바구니 담기 배너추가, 토스트 라이브러리 추가
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/elements/BuyBoxForMobile/BuyBoxOption.tsx
  src/components/elements/BuyBoxForMobile/BuyBoxOption.type.tsx
  src/components/elements/BuyModal/BuyModal.tsx
  src/components/elements/BuyModal/BuyModal.type.ts
  src/components/elements/ToasterWrapper/ToastWrapper.tsx
  src/components/layouts/Modal/CartSuccessModal.tsx
  src/features/buyModal/buyModalAction.tsx
  src/features/cartClientControl/cartClientControl.tsx
  src/features/cartItemCountIcon/CartItemCountIcon.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#176 ♻️ refactor: 2차 배포건 리팩토링
  public/svgs/notice.svg
  public/svgs/pot.svg
  src/app/(accounts)/(user)/mypage/page.tsx
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/result/[_id]/detail/page.tsx
  src/app/page.tsx
  src/components/elements/ProductDetailInfo/ProductDetailInfo.tsx
  src/components/elements/ProductItem/Badge/Badge.tsx
  src/components/elements/ProductItem/Badge/Badge.type.tsx
  src/components/elements/ProductItem/Item/CropItem.tsx
  src/components/elements/ProductItem/Item/ExperienceItem.tsx
  src/components/elements/ProductItem/Item/GardenItem.tsx
  src/components/elements/ProductItem/List/ProductItemList.tsx
  src/components/elements/ProductLink/ProductLink.tsx
  src/components/layouts/Banner/SlideBanner.tsx
  src/features/productListClientControl/productListClientControl.tsx
  src/shared/api/dbinit/team/data.js
  src/shared/types/product.ts
Labels: 🐛 Task: 버그 해결, ✅ Task: 기능 개발, ⚙️ Task: 리팩토링

#184 ♻️ refactor: 2차 배포건 추가 리팩토링
  src/components/elements/LoginItem/LoginInput.tsx
Labels: ⚙️ Task: 리팩토링

#188 ♻️ refactor: 2차 배포건 리팩토링 및 리뷰,qna 작성 기능 완료 (사진 첨부는 테스트중)
  src/app/(exploring)/search/result/[_id]/loading.tsx
  src/app/(exploring)/search/result/[_id]/qna/page.tsx
  src/app/(exploring)/search/result/[_id]/review/page.tsx
  src/components/elements/OrderItem/OrderItem.tsx
  src/components/elements/OrderItem/OrderItem.type.ts
  src/components/elements/QnaItem/QnaItem.tsx
  src/components/layouts/SortBar/Sortbar.type.ts
  src/features/orderClientControl/orderClientControl.tsx
  src/features/qnaClientControl/productCateory.tsx
  src/features/qnaClientControl/qnaClientControl.tsx
  src/features/reviewClientControl/reviewClientControl.tsx
  src/shared/data/actions/file.ts
  src/shared/data/actions/post.ts
  src/shared/data/actions/replies.ts
  src/shared/data/functions/file.ts
  src/shared/data/functions/post.ts
  src/shared/types/file.ts
  src/shared/types/order.ts
  src/shared/types/post.ts
  src/shared/types/qna.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#187 ♻️ refactor: 2차 배포건 리팩토링 및 검색 기능 개발(진행 중)
  src/app/(accounts)/(seller)/office/analytics/page.tsx
  src/app/(accounts)/(seller)/office/orders/page.tsx
  src/app/(accounts)/(seller)/office/products/edit/page.tsx
  src/app/(accounts)/(seller)/office/products/new/page.tsx
  src/app/(accounts)/(seller)/office/products/select/new/page.tsx
  src/app/(accounts)/(seller)/office/products/select/page.tsx
  src/app/(accounts)/register/seller/registerForm.tsx
  src/app/(exploring)/search/page.tsx
  src/app/(exploring)/search/result/page.tsx
  src/app/board/review/edit/page.tsx
  src/app/board/review/new/page.tsx
  src/app/board/review/page.tsx
  src/components/elements/HamburgerIcon/HamburgerIcon.tsx
  src/components/elements/LoginItem/LoginInput.tsx
  src/components/elements/RelatedKeywordItem/RelatedKeywordItem.type.tsx
  src/components/elements/SearchForm/SearchForm.tsx
  src/components/elements/TopRatedItem/TopRatedItem.tsx
  src/features/productListFilteredKeyword/productListFilteredKeyword.tsx
  src/shared/store/keywordStore.ts
  src/shared/types/product.ts
  src/shared/types/user.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#193 ♻️ refactor : 자동 로그인 기능 상세 구현
  src/app/layout.tsx
  src/components/layouts/Login/LoginForm.tsx
  src/features/initAuthStore/initAuthStore.tsx
  src/shared/store/authStore.ts
Labels: 🐛 Task: 버그 해결, ⚙️ Task: 리팩토링

#194 ✨ feat: 검색 기능 및 필터링 기능 구현 완료(정렬 관련 컴포넌트 기능 개발 필요)
  src/app/(exploring)/search/page.tsx
  src/app/(exploring)/search/result/page.tsx
  src/components/elements/ProductItem/List/ProductItemList.tsx
  src/components/elements/SearchForm/SearchForm.tsx
  src/features/goBackIcon/goBackIcon.tsx
  src/features/productListFilteredKeyword/productListFilteredKeyword.tsx
Labels: ✅ Task: 기능 개발, ⚙️ Task: 리팩토링

#202 ✨ feat: 상품 탐색, 검색 페이지 필터링 및 정렬 기능 추가
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/elements/HamburgerIcon/HamburgerIcon.tsx
  src/components/elements/LogoutIcon/LogoutIcon.tsx
  src/components/elements/SearchForm/SearchForm.tsx
  src/features/cartItemCountIcon/CartItemCountIcon.tsx
  src/features/getRecentSearchKeyword/GetRecentSearchKeyword.tsx
  src/features/productListClientControl/productListClientControl.tsx
  src/features/productListFilteredKeyword/productListFilteredKeyword.tsx
  src/shared/store/keywordStore.ts
  src/shared/types/keyword.ts
  src/shared/types/sorting.ts
Labels: ✅ Task: 기능 개발, ⚙️ Task: 리팩토링

#211 ✨ feat: 판매자 전용페이지(백오피스) 페이지 UI 완성 (기능 X)
  src/app/(accounts)/(seller)/office/orders/page.tsx
  src/app/(accounts)/(seller)/office/page.tsx
  src/app/(accounts)/(seller)/office/payments/page.tsx
  src/app/(accounts)/(seller)/office/products/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/crop/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/experience/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/gardening/page.tsx
  src/app/(accounts)/(seller)/office/products/select/new/page.tsx
  src/app/(accounts)/(seller)/office/products/select/page.tsx
  src/app/page.tsx
  src/components/elements/HamburgerIcon/HamburgerIcon.tsx
  src/components/elements/HotMarkIcon/HotMarkIcon.tsx
  src/components/elements/LogoutIcon/LogoutIcon.tsx
  src/components/layouts/Header/LinkHeader.tsx
  src/components/layouts/Login/BackOfficeSectionDependsOnLoginStatus.tsx
  src/components/layouts/Login/LoginForm.tsx
Labels: ✅ Task: UI 개선

#213 ♻️ refactor: 2차 배포건 추가 리팩토링
  src/app/(accounts)/register/seller/registerForm.tsx
  src/app/(accounts)/register/user/registerForm.tsx
  src/components/elements/LoginItem/LoginInput.tsx
  src/components/elements/LoginItem/LoginInput.type.tsx
  src/components/elements/LogoutIcon/LogoutIcon.tsx
Labels: 🐛 Task: 버그 해결, ⚙️ Task: 리팩토링

#223 ✨ feat: 판매자 관리페이지 하위 농산물 상품 등록 페이지 UI 작업 완료
  src/app/(accounts)/(seller)/office/products/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/crop/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/experience/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/gardening/page.tsx
  src/components/elements/CheckOption/IncludedItemsCheckBok.tsx
  src/components/elements/LoginItem/Input.tsx
  src/components/elements/OrderOption/SellerProductEditOption.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#229 ✨ feat: 판매자 관리페이지(메인) DB 업데이트 기능 구현 완료
  src/components/layouts/Login/BackOfficeSectionDependsOnLoginStatus.tsx
  src/shared/data/actions/order.ts
  src/shared/data/functions/order.ts
  src/shared/data/functions/product.ts
Labels: ✅ Task: 기능 개발

#233 ✨ feat: 판매자 관리페이지 중 주문내역 페이지 DB 업데이트 및 필터링 기능 구현 완료
  src/app/(accounts)/(seller)/office/orders/page.tsx
  src/components/elements/OrderItem/OrderItem.tsx
  src/components/elements/OrderItem/OrderItemForSeller.tsx
  src/components/elements/OrderOption/OrderOption.tsx
  src/features/cartClientControl/cartClientControl.tsx
  src/features/officeOrderClientControl/officeOrderClientControl.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#239 ✨ feat: 상품 등록 기능 구현 완료
  src/app/(accounts)/(seller)/office/products/select/editor/crop/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/experience/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/gardening/page.tsx
  src/components/elements/BuyModal/BuyModal.tsx
  src/components/elements/LoginItem/Input.tsx
  src/components/elements/OrderOption/SellerProductEditOption.tsx
  src/components/elements/PickListItem/PickListItem.tsx
  src/components/elements/ProductDetailInfo/ProductDetailInfo.tsx
  src/components/elements/ProductItem/List/ProductItemList.tsx
  src/features/ProductPostClientControl/CropProductPostClientControl.tsx
  src/features/ProductPostClientControl/ExperienceProductPostClientControl.tsx
  src/features/ProductPostClientControl/GardeningProductPostClientControl.tsx
  src/shared/data/actions/product.ts
  src/shared/types/product.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#240 ✨feat : 판매자 관리페이지 상품 관리 필터링 기능 구현
  src/app/(accounts)/(seller)/office/products/page.tsx
  src/components/elements/ProductItem/List/ProductItemListForSeller.tsx
  src/components/elements/ProductItem/List/ProductItemListForSeller.type.ts
  src/features/sellerProductClientControl/sellerProductClientControl.tsx
Labels: ✅ Task: 기능 개발, 🔴 Priority: High

#241 ✨ feat: 텃밭 기능 완성
  public/images/gardening/dummy-001.png
  public/images/gardening/dummy-002.png
  public/images/gardening/gardening-001.png
  public/svgs/growing.svg
  public/svgs/harvest.svg
  public/svgs/seeding.svg
  public/svgs/sprouting.svg
  src/app/(accounts)/(user)/mypage/gardening/page.tsx
  src/app/(accounts)/(user)/mypage/mygarden/[_id]/page.tsx
  src/app/(accounts)/(user)/mypage/mygarden/layout.tsx
  src/app/(accounts)/(user)/mypage/mygarden/page.tsx
  src/app/(accounts)/(user)/mypage/page.tsx
  src/app/globals.css
  src/components/elements/GardenItemForMyGarden/GardenItemForMyGarden.tsx
  src/components/elements/GardenItemForMyGarden/GardenItemListForMyGarden.tsx
  src/components/elements/PeriodItem/PeriodItem.tsx
  src/components/elements/ProgressBar/ProgressBar.tsx
  src/components/layouts/Header/LinkHeader.tsx
  src/shared/types/order.ts
  src/shared/types/product.ts
  src/utils/getDaysFromToday/getDaysFromToday.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#243 ✨ feat: 판매자 Qna 페이지 구현 완료
  src/app/(accounts)/(seller)/office/qnas/page.tsx
  src/components/elements/OrderOption/sellerQnaOption.tsx
  src/components/elements/QnaItem/SellerQnaItem.tsx
  src/components/layouts/Login/BackOfficeSectionDependsOnLoginStatus.tsx
  src/features/sellerQnaPageClientControl/sellerQnaPageClientControl.tsx
  src/shared/types/post.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#245 🐛 bugfix: 빌드 오류 및 기능 오류건 수정
  src/components/elements/GardenItemForMyGarden/GardenItemListForMyGarden.tsx
  src/components/elements/ProgressBar/ProgressBar.tsx
  src/components/layouts/Footer/Footer.tsx
Labels: 🐛 Task: 버그 해결
