Repository FRONTENDBOOTCAMP-13th/Final-05-oguogu, pull requests merged in 2025-08, with the labels that each got.

#260 ✨ feat: DB 변경된 형식으로 수정, 공지사항, 자주하는 질문 page 구현, 상세페이지 DB 반영
  next.config.ts
  src/app/board/notice/[_id]/page.tsx
  src/app/board/notice/page.tsx
  src/app/board/qna/[_id]/page.tsx
  src/app/board/qna/page.tsx
  src/components/elements/ProductDetailInfo/ProductDetailInfo.tsx
  src/components/elements/ProductItem/Item/CropItem.tsx
  src/components/elements/ProductItem/Item/ExperienceItem.tsx
  src/components/elements/ProductItem/Item/GardenItem.tsx
  src/components/elements/QnaItem/QnaItem.tsx
  src/components/elements/ReviewItem/ReviewItem.tsx
  src/components/elements/boardItem/noticeItem.tsx
  src/components/elements/boardItem/qnaItem.tsx
  src/features/ProductPostClientControl/ExperienceProductPostClientControl.tsx
  src/features/ProductPostClientControl/GardeningProductPostClientControl.tsx
  src/features/orderClientControl/orderClientControl.tsx
  src/shared/api/dbinit/team/data.json
  src/shared/types/post.ts
  src/shared/types/product.ts
  src/shared/types/user.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#261 ♻️ refactor: 3차 빌드 오류 내용 중 일부 해결, 수정 및 개선
  src/app/(accounts)/register/seller/registerForm.tsx
  src/components/elements/AccoutItem/AccountForm.tsx
  src/components/elements/AccoutItem/AccountItem.tsx
  src/components/elements/LoginItem/LoginInput.tsx
  src/components/elements/LoginItem/LoginInput.type.tsx
  src/components/elements/OrderItem/OrderItem.tsx
  src/components/elements/ProductItem/Badge/Badge.tsx
  src/components/elements/ProductItem/Item/CropItem.tsx
  src/components/elements/ProductItem/Item/GardenItem.tsx
  src/features/orderClientControl/orderClientControl.tsx
  src/features/productListClientControl/productListClientControl.tsx
  src/features/productListFilteredKeyword/productListFilteredKeyword.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#265 Refactor/3rd build/ws
  src/components/elements/ProductItem/List/ProductItemListForSeller.tsx
  src/components/elements/ProductItem/List/ProductItemListForSeller.type.ts
  src/features/sellerProductClientControl/sellerProductClientControl.tsx
Labels: 🐛 Task: 버그 해결, ✅ Task: 기능 개발, ⚙️ Task: 리팩토링

#267 ✨ feat: Navigation 기능 구현, SlideBanner 링크 기능 추가, 기타 스타일링 수정
  src/app/(accounts)/(seller)/office/products/select/page.tsx
  src/app/(accounts)/register/page.tsx
  src/app/page.tsx
  src/components/elements/BannerItem/SlideBannerItem.tsx
  src/components/elements/BannerItem/SlideBannerItem.type.tsx
  src/components/elements/CategoryItem/CategoryItem.tsx
  src/components/elements/LoginItem/LoginInput.tsx
  src/components/elements/NavigationItem/NavigationItem.tsx
  src/components/elements/NavigationItem/NavigationItem.type.tsx
  src/components/elements/RegisterItem/RegisterCardItem.tsx
  src/components/layouts/Banner/SlideBanner.tsx
  src/components/layouts/Login/LoginForm.tsx
  src/components/layouts/Navigation/Navigation.tsx
Labels: ✅ Task: 기능 개발

#268 ♻️ refactor: 3차 배포 리팩토링 (사진 업로드 오류 문제 해결)
  src/components/elements/ReviewItem/ReviewItem.tsx
  src/components/layouts/Modal/OrderSucessModal.tsx
  src/features/ProductPostClientControl/GardeningProductPostClientControl.tsx
  src/features/cartClientControl/cartClientControl.tsx
Labels: ⚙️ Task: 리팩토링

#270 ✨ feat: 메인 페이지 요소 추가 완료
  src/app/page.tsx
  src/components/elements/ReviewItem/ReviewItem.tsx
  src/components/elements/ReviewItem/ReviewItemCard.tsx
  src/components/elements/boardItem/noticeItem.tsx
  src/components/layouts/Navigation/Navigation.tsx
  src/shared/types/review.ts
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선

#272 ✨ feat: 메타데이터 추가 작업 진행 (파비콘 이미지 수정 필요)
  public/images/favicon.ico
  public/images/favicon.png
  public/svgs/59logo.svg
  src/app/(accounts)/(seller)/office/orders/page.tsx
  src/app/(accounts)/(seller)/office/page.tsx
  src/app/(accounts)/(seller)/office/payments/page.tsx
  src/app/(accounts)/(seller)/office/products/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/crop/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/experience/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/gardening/page.tsx
  src/app/(accounts)/(seller)/office/products/select/page.tsx
  src/app/(accounts)/(seller)/office/qnas/page.tsx
  src/app/(accounts)/(user)/mypage/cart/page.tsx
  src/app/(accounts)/(user)/mypage/mygarden/[_id]/page.tsx
  src/app/(accounts)/(user)/mypage/mygarden/page.tsx
  src/app/(accounts)/(user)/mypage/order/page.tsx
  src/app/(accounts)/(user)/mypage/page.tsx
  src/app/(accounts)/(user)/mypage/pick/page.tsx
  src/app/(accounts)/account/edit/page.tsx
  src/app/(accounts)/account/page.tsx
  src/app/(accounts)/login/page.tsx
  src/app/(accounts)/register/page.tsx
  src/app/(accounts)/register/seller/page.tsx
  src/app/(accounts)/register/user/page.tsx
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/page.tsx
  src/app/(exploring)/search/result/[_id]/detail/page.tsx
  src/app/(exploring)/search/result/[_id]/qna/page.tsx
  src/app/(exploring)/search/result/[_id]/review/page.tsx
  src/app/board/notice/[_id]/page.tsx
  src/app/board/notice/page.tsx
  src/app/board/qna/[_id]/page.tsx
  src/app/board/qna/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
Labels: ⚙️ Task: 리팩토링

#280 ♻️ refactor: 4차 배포건 리팩토링
  src/app/(accounts)/(seller)/office/mygarden/[_id]/page.tsx
  src/app/(accounts)/(seller)/office/mygarden/page.tsx
  src/app/(accounts)/(seller)/office/page.tsx
  src/app/(accounts)/(user)/mypage/mygarden/[_id]/page.tsx
  src/app/board/notice/[_id]/page.tsx
  src/app/board/notice/page.tsx
  src/app/board/qna/[_id]/page.tsx
  src/app/page.tsx
  src/components/elements/BannerItem/SlideBannerItem.tsx
  src/components/elements/CategoryItem/CategoryItem.tsx
  src/components/elements/CuteLoading/CuteLoading.tsx
  src/components/elements/GardenItemForMyGarden/GardenItemForMyGarden.tsx
  src/components/elements/GardenItemForMyGarden/GardenItemForSeller.tsx
  src/components/elements/OrderItem/OrderItemForSeller.tsx
  src/components/elements/Path/Path.tsx
  src/components/elements/PeriodItem/PeriodItem.tsx
  src/components/elements/PickListItem/PickListItem.tsx
  src/components/elements/ProductDetailInfo/ProductDetailInfo.tsx
  src/components/elements/ProductItem/Item/CropItem.tsx
  src/components/elements/ProductItem/Item/ExperienceItem.tsx
  src/components/elements/ProductItem/Item/GardenItem.tsx
  src/components/elements/ProductItem/Item/GardenItemIcon.tsx
  src/components/elements/RegisterItem/RegisterCardItem.tsx
  src/components/elements/TopRatedItem/TopRatedItem.tsx
  src/components/layouts/Login/MyPageSectionDependsOnLoginStatus.tsx
  src/components/layouts/SortBar/Sortbar.tsx
  src/features/addPeriodForm/AddPeriodForm.tsx
  src/features/goBackIcon/goBackIcon.tsx
  src/features/officeOrderClientControl/officeOrderClientControl.tsx
  src/features/reviewClientControl/reviewClientControl.tsx
  src/features/toggleOfficePageForSeller/ToggleOfficePageForSeller.tsx
  src/shared/types/order.ts
Labels: 🐛 Task: 버그 해결, ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#285 💄style : 로그인 폼 요소 정리
  src/app/(accounts)/register/page.tsx
  src/components/elements/ProductLink/ProductLink.tsx
  src/components/elements/ProductLink/ProductLink.type.tsx
  src/components/layouts/Login/LoginForm.tsx
Labels: ✅ Task: UI 개선

#286 🐛 bugfix: 관리페이지 토글 버튼이 사용자에게도 표시되는 오류 수정 및 메타데이터 정보 일부 수정
  src/app/(accounts)/(seller)/office/orders/page.tsx
  src/app/(accounts)/(seller)/office/page.tsx
  src/app/(accounts)/(seller)/office/payments/page.tsx
  src/app/(accounts)/(seller)/office/products/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/crop/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/experience/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/gardening/page.tsx
  src/app/(accounts)/(seller)/office/products/select/page.tsx
  src/app/(accounts)/(seller)/office/qnas/page.tsx
  src/app/(accounts)/(user)/mypage/cart/page.tsx
  src/app/(accounts)/(user)/mypage/mygarden/[_id]/page.tsx
  src/app/(accounts)/(user)/mypage/mygarden/page.tsx
  src/app/(accounts)/(user)/mypage/order/page.tsx
  src/app/(accounts)/(user)/mypage/page.tsx
  src/app/(accounts)/(user)/mypage/pick/page.tsx
  src/app/(accounts)/account/edit/page.tsx
  src/app/(accounts)/account/page.tsx
  src/app/(accounts)/login/page.tsx
  src/app/(accounts)/register/page.tsx
  src/app/(accounts)/register/seller/page.tsx
  src/app/(accounts)/register/user/page.tsx
  src/app/(exploring)/garden/[seller_id]/page.tsx
  src/app/(exploring)/product/[type]/page.tsx
  src/app/(exploring)/search/page.tsx
  src/app/(exploring)/search/result/[_id]/detail/page.tsx
  src/app/(exploring)/search/result/[_id]/qna/page.tsx
  src/app/(exploring)/search/result/[_id]/review/page.tsx
  src/app/(exploring)/search/result/page.tsx
  src/app/board/notice/[_id]/page.tsx
  src/app/board/notice/page.tsx
  src/app/board/qna/[_id]/page.tsx
  src/app/board/qna/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/features/toggleOfficePageForSeller/ToggleOfficePageForSeller.tsx
Labels: 🐛 Task: 버그 해결, ⚙️ Task: 리팩토링

#289 ✨ feat: 이미지 경로 수정
  src/app/(exploring)/search/result/[_id]/detail/page.tsx
  src/components/elements/OrderItem/OrderItem.tsx
  src/components/elements/OrderItem/OrderItemForSeller.tsx
  src/components/elements/PickListItem/PickListItem.tsx
  src/components/elements/cardItem/cardItem.tsx
  src/shared/api/dbinit/team/data.json
  src/shared/types/cart.ts
Labels: ⚙️ Task: 리팩토링

#288 🩹 fix: 주석 텍스트 주석 처리
  src/app/page.tsx
Labels: Task: 기타

#296 🩹 fix: 빌드 에러 코드 삭제
  src/components/elements/BannerItem/SlideBannerItem.tsx
Labels: 🐛 Task: 버그 해결

#301 🩹 fix: 모바일에서 동영상 배너 이슈 해결
  src/components/elements/BannerItem/SlideBannerItem.tsx
Labels: 🐛 Task: 버그 해결

#308 ♻️ refactor: 5차 배포 기능 개선 및 텃밭 DB 작업
  public/images/gardeningHistory/growing-001.png
  public/images/gardeningHistory/growing-002.png
  public/images/gardeningHistory/growing-003.png
  public/images/gardeningHistory/growing-004.png
  public/images/gardeningHistory/harvested-001.png
  public/images/gardeningHistory/harvested-002.png
  public/images/gardeningHistory/seeding-001.png
  public/images/gardeningHistory/seeding-002.png
  public/images/gardeningHistory/seeding-003.png
  public/images/gardeningHistory/seeding-004.png
  public/images/gardeningHistory/sprouting-001.png
  public/images/gardeningHistory/sprouting-002.png
  public/images/gardeningHistory/sprouting-003.png
  public/images/gardeningHistory/sprouting-004.png
  src/app/(accounts)/(user)/mypage/mygarden/[_id]/page.tsx
  src/app/page.tsx
  src/components/elements/BannerItem/SlideBannerItem.tsx
  src/components/elements/BuyModal/BuyModal.tsx
  src/components/elements/CommonTitleItem/Title.tsx
  src/components/elements/GardenItemForMyGarden/GardenItemForMyGarden.tsx
  src/components/elements/GardenItemForMyGarden/GardenItemListForMyGarden.tsx
  src/components/elements/OrderItem/OrderItem.tsx
  src/components/elements/PeriodItem/PeriodItem.tsx
  src/components/elements/TopRatedItem/TopRatedItem.tsx
  src/components/elements/cardItem/cardItem.tsx
  src/components/layouts/Banner/SlideBanner.tsx
  src/components/layouts/Navigation/Navigation.tsx
  src/features/goBackIcon/goBackIcon.tsx
  src/features/toggleOfficePageForSeller/ToggleOfficePageForSeller.tsx
  src/shared/api/dbinit/team/data.json
  src/shared/api/dbinit/team/uploadFiles/garden/Corn.png
  src/shared/api/dbinit/team/uploadFiles/garden/Melon.png
  src/shared/api/dbinit/team/uploadFiles/garden/Tomato-002.png
  src/shared/api/dbinit/team/uploadFiles/garden/Watermelon.png
  src/shared/types/cart.ts
Labels: ✅ Task: 기능 개발, ⚙️ Task: 리팩토링

#314 ♻️ refactor: 6차 배포 리팩토링 및 기능 개선
  src/app/(accounts)/(seller)/office/mygarden/[_id]/page.tsx
  src/app/(accounts)/(seller)/office/page.tsx
  src/app/board/notice/[_id]/page.tsx
  src/app/board/notice/page.tsx
  src/app/board/qna/[_id]/page.tsx
  src/components/elements/AccoutItem/AccountItem.tsx
  src/components/elements/BuyModal/BuyModal.tsx
  src/components/elements/ProductItem/Item/CropItem.tsx
  src/components/elements/ProductItem/Item/ExperienceItem.tsx
  src/components/elements/ProductItem/Item/GardenItem.tsx
  src/components/elements/ProductItem/List/ProductItemListForSeller.tsx
  src/components/elements/QnaItem/SellerQnaItem.tsx
  src/components/elements/boardItem/noticeItem.tsx
  src/components/elements/boardItem/qnaItem.tsx
  src/components/layouts/Login/BackOfficeSectionDependsOnLoginStatus.tsx
  src/components/layouts/Login/MyPageSectionDependsOnLoginStatus.tsx
  src/features/cartItemCountIcon/CartItemCountIcon.tsx
  src/features/toggleOfficePageForSeller/ToggleOfficePageForSeller.tsx
Labels: 🐛 Task: 버그 해결, ✅ Task: 기능 개발, ⚙️ Task: 리팩토링

#315 ♻️ refactor: 6차 배포 리팩토링 및 기능 개선
  package-lock.json
  package.json
  public/images/meta/favicon.png
  public/metadata.png
  public/metadata_og.png
  src/app/(exploring)/search/result/[_id]/detail/page.tsx
  src/app/(exploring)/search/result/[_id]/review/page.tsx
  src/app/board/notice/page.tsx
  src/app/layout.tsx
  src/components/elements/OrderItem/OrderItem.tsx
  src/components/elements/OrderItem/OrderItemForSeller.tsx
  src/components/elements/ProductItem/Item/CropItem.tsx
  src/components/elements/ProductItem/Item/ExperienceItem.tsx
  src/components/elements/ProductItem/Item/GardenItem.tsx
  src/components/elements/boardItem/noticeItem.tsx
  src/components/elements/cardItem/cardItem.tsx
  src/components/layouts/Banner/SlideBanner.tsx
  src/components/layouts/SortBar/Sortbar.tsx
Labels: ✅ Task: 기능 개발, ✅ Task: UI 개선, ⚙️ Task: 리팩토링

#321 🩹fix : 상품 관리 페이지 수정 버튼 경로 연결 및 aria-label 수정
  src/components/elements/ProductItem/List/ProductItemListForSeller.tsx
Labels: ⚙️ Task: 리팩토링

#325 🚑 hotfix: 회원가입 생일 유효성 검사 추가
  src/app/(accounts)/register/user/registerForm.tsx
  src/components/elements/LoginItem/LoginInput.tsx
Labels: 🐛 Task: 버그 해결

#324 🩹 fix: data.json 적상추 텃밭 상품 Period 추가
  src/shared/api/dbinit/team/data.json
Labels: 🐛 Task: 버그 해결, Task: 기타

#327 🩹 fix: Suspense 추가 (빌드 에러)
  src/app/(accounts)/(seller)/office/products/select/editor/crop/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/experience/page.tsx
  src/app/(accounts)/(seller)/office/products/select/editor/gardening/page.tsx
Labels: 🐛 Task: 버그 해결

#328 🚑 hotfix: 회원가입 주소 유효성 검사 추가
  src/app/(accounts)/register/user/registerForm.tsx
Labels: 🐛 Task: 버그 해결

#334 🩹 fix: 찜하기 회사명 표기 오류 해결
  src/components/elements/PickListItem/PickListItem.tsx
  src/features/pickList/pickList.tsx
Labels: ⚙️ Task: 리팩토링
